import 'dart:convert';
import 'dart:io';

import 'package:analyzer/dart/analysis/analysis_context_collection.dart';
import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/type.dart';
import 'package:crypto/crypto.dart';

import 'public_api_compatibility.dart';
export 'public_api_compatibility.dart';

Future<String> buildPublicApiSnapshot(Directory repositoryRoot) async {
  final root = repositoryRoot.absolute;
  final library = File.fromUri(root.uri.resolve(publicLibraryPath));
  final libraryPath = library.path;
  if (!library.existsSync()) {
    throw StateError('Missing public library: $libraryPath');
  }

  final collection = AnalysisContextCollection(
    includedPaths: [root.path],
    sdkPath: _findDartSdkPath(),
  );
  try {
    final context = collection.contextFor(libraryPath);
    final result = await context.currentSession.getResolvedLibrary(libraryPath);
    if (result is! ResolvedLibraryResult) {
      throw StateError(
        'Analyzer could not resolve $publicLibraryPath: '
        '${result.runtimeType}',
      );
    }

    final elements =
        result.element.exportNamespace.definedNames2.values
            .where((element) => element.isPublic)
            .toSet()
            .toList()
          ..sort(
            (left, right) => left.displayName.compareTo(right.displayName),
          );

    final body = StringBuffer();
    for (final element in elements) {
      _writeElement(body, element);
      body.writeln();
    }
    final bodyText = body.toString();
    final sourceChecksum = buildPublicApiInputChecksum(repositoryRoot);
    final bodyChecksum = sha256.convert(utf8.encode(bodyText)).toString();
    final buffer = StringBuffer()
      ..writeln('# BLDS public API snapshot')
      ..writeln(
        '# Generated by: dart run tool/public_api_snapshot.dart --write',
      )
      ..writeln('# Check with: dart run tool/public_api_snapshot.dart --check')
      ..writeln('# Source: package:blab_design_system/blab_design_system.dart')
      ..writeln('# Analyzer dependency is pinned in pubspec.yaml.')
      ..writeln('# Public API input checksum (SHA-256): $sourceChecksum')
      ..writeln('# Content checksum (SHA-256, body only): $bodyChecksum')
      ..writeln()
      ..write(bodyText);

    return buffer.toString();
  } finally {
    await collection.dispose();
  }
}

String _findDartSdkPath() {
  var directory = File(Platform.resolvedExecutable).parent;
  while (true) {
    if (isDartSdkDirectory(directory)) {
      return directory.path;
    }

    final siblingSdk = Directory(
      '${directory.path}${Platform.pathSeparator}dart-sdk',
    );
    if (isDartSdkDirectory(siblingSdk)) {
      return siblingSdk.path;
    }

    final parent = directory.parent;
    if (parent.path == directory.path) {
      break;
    }
    directory = parent;
  }

  throw StateError(
    'Could not locate the Dart SDK from ${Platform.resolvedExecutable}.',
  );
}

bool isDartSdkDirectory(Directory directory, {String? executableName}) {
  final dartExecutable =
      executableName ?? (Platform.isWindows ? 'dart.exe' : 'dart');
  return File(
        '${directory.path}${Platform.pathSeparator}bin'
        '${Platform.pathSeparator}$dartExecutable',
      ).existsSync() &&
      Directory('${directory.path}${Platform.pathSeparator}lib').existsSync();
}

void _writeElement(StringBuffer buffer, Element element) {
  switch (element) {
    case EnumElement():
      _writeEnum(buffer, element);
    case ClassElement():
      _writeClass(buffer, element);
    case MixinElement():
      _writeMixin(buffer, element);
    case ExtensionElement():
      _writeExtension(buffer, element);
    case ExtensionTypeElement():
      _writeExtensionType(buffer, element);
    case TypeAliasElement():
      buffer.writeln(
        'typedef ${element.displayName}${_typeParameters(element)} = '
        '${_type(element.aliasedType)}',
      );
    case TopLevelFunctionElement():
      buffer.writeln(
        'function ${_type(element.returnType)} ${element.displayName}'
        '${_typeParameters(element)}${_parameters(element.formalParameters)}',
      );
    case TopLevelVariableElement():
      _writeVariable(buffer, element, indent: '');
    case GetterElement() when element.isOriginDeclaration:
      _writeGetter(buffer, element, indent: '');
    case SetterElement() when element.isOriginDeclaration:
      _writeSetter(buffer, element, indent: '');
    default:
      throw StateError(
        'Unsupported exported element ${element.runtimeType}: '
        '${element.displayName}',
      );
  }
}

void _writeClass(StringBuffer buffer, ClassElement element) {
  final modifiers = <String>[
    if (element.isAbstract) 'abstract',
    if (element.isBase) 'base',
    if (element.isFinal) 'final',
    if (element.isInterface) 'interface',
    if (element.isSealed) 'sealed',
  ];
  final prefix = modifiers.isEmpty ? '' : '${modifiers.join(' ')} ';
  buffer.write(
    '${prefix}class ${element.displayName}${_typeParameters(element)}',
  );
  _writeRelationships(buffer, element);
  buffer.writeln();
  _writeInterfaceBody(buffer, element);
}

void _writeEnum(StringBuffer buffer, EnumElement element) {
  buffer.write('enum ${element.displayName}${_typeParameters(element)}');
  _writeRelationships(buffer, element, includeSupertype: false);
  buffer.writeln();

  final constants = element.constants
      .where((constant) => constant.isPublic)
      .map((constant) => constant.displayName)
      .toList();
  buffer.writeln('  values: ${constants.join(', ')}');
  _writeInterfaceBody(buffer, element, includeEnumConstants: false);
}

void _writeMixin(StringBuffer buffer, MixinElement element) {
  buffer.write('mixin ${element.displayName}${_typeParameters(element)}');
  final constraints = element.superclassConstraints.map(_type).toList();
  if (constraints.isNotEmpty) {
    buffer.write(' on ${constraints.join(', ')}');
  }
  if (element.interfaces.isNotEmpty) {
    buffer.write(' implements ${element.interfaces.map(_type).join(', ')}');
  }
  buffer.writeln();
  _writeInstanceBody(buffer, element);
}

void _writeExtension(StringBuffer buffer, ExtensionElement element) {
  buffer.writeln(
    'extension ${element.displayName}${_typeParameters(element)} '
    'on ${_type(element.extendedType)}',
  );
  _writeInstanceBody(buffer, element);
}

void _writeExtensionType(StringBuffer buffer, ExtensionTypeElement element) {
  buffer.write(
    'extension type ${element.displayName}${_typeParameters(element)}',
  );
  _writeRelationships(buffer, element, includeSupertype: false);
  buffer.writeln();
  _writeInterfaceBody(buffer, element);
}

void _writeRelationships(
  StringBuffer buffer,
  InterfaceElement element, {
  bool includeSupertype = true,
}) {
  final supertype = element.supertype;
  if (includeSupertype &&
      supertype != null &&
      supertype.element.displayName != 'Object') {
    buffer.write(' extends ${_type(supertype)}');
  }
  if (element.mixins.isNotEmpty) {
    buffer.write(' with ${element.mixins.map(_type).join(', ')}');
  }
  if (element.interfaces.isNotEmpty) {
    buffer.write(' implements ${element.interfaces.map(_type).join(', ')}');
  }
}

void _writeInterfaceBody(
  StringBuffer buffer,
  InterfaceElement element, {
  bool includeEnumConstants = true,
}) {
  final constructors =
      element.constructors.where((constructor) => constructor.isPublic).toList()
        ..sort((left, right) => left.displayName.compareTo(right.displayName));
  for (final constructor in constructors) {
    final modifiers = <String>[
      if (constructor.isConst) 'const',
      if (constructor.isFactory) 'factory',
    ];
    final prefix = modifiers.isEmpty ? '' : '${modifiers.join(' ')} ';
    final constructorName = formatPublicApiConstructorName(
      interfaceName: element.displayName,
      constructorName: constructor.name ?? 'new',
    );
    buffer.writeln(
      '  constructor $prefix$constructorName'
      '${_typeParameters(constructor)}'
      '${_parameters(constructor.formalParameters)}',
    );
  }

  _writeInstanceBody(
    buffer,
    element,
    includeEnumConstants: includeEnumConstants,
  );
}

String formatPublicApiConstructorName({
  required String interfaceName,
  required String constructorName,
}) {
  return constructorName == 'new' || constructorName.isEmpty
      ? interfaceName
      : '$interfaceName.$constructorName';
}

void _writeInstanceBody(
  StringBuffer buffer,
  InstanceElement element, {
  bool includeEnumConstants = true,
}) {
  final fields =
      element.fields
          .where(
            (field) =>
                field.isPublic &&
                field.isOriginDeclaration &&
                (includeEnumConstants || !field.isEnumConstant) &&
                !field.isOriginEnumValues,
          )
          .toList()
        ..sort((left, right) => left.displayName.compareTo(right.displayName));
  for (final field in fields) {
    _writeVariable(buffer, field, indent: '  ');
  }

  final getters =
      element.getters
          .where((getter) => getter.isPublic && getter.isOriginDeclaration)
          .toList()
        ..sort((left, right) => left.displayName.compareTo(right.displayName));
  for (final getter in getters) {
    _writeGetter(buffer, getter, indent: '  ');
  }

  final setters =
      element.setters
          .where((setter) => setter.isPublic && setter.isOriginDeclaration)
          .toList()
        ..sort((left, right) => left.displayName.compareTo(right.displayName));
  for (final setter in setters) {
    _writeSetter(buffer, setter, indent: '  ');
  }

  final methods =
      element.methods
          .where((method) => method.isPublic && method.isOriginDeclaration)
          .toList()
        ..sort((left, right) => left.displayName.compareTo(right.displayName));
  for (final method in methods) {
    final staticPrefix = method.isStatic ? 'static ' : '';
    buffer.writeln(
      '  method $staticPrefix${_type(method.returnType)} '
      '${method.displayName}${_typeParameters(method)}'
      '${_parameters(method.formalParameters)}',
    );
  }
}

void _writeVariable(
  StringBuffer buffer,
  VariableElement element, {
  required String indent,
}) {
  final modifiers = <String>[
    if (element.isStatic) 'static',
    if (element.isLate) 'late',
    if (element.isConst) 'const' else if (element.isFinal) 'final',
  ];
  final prefix = modifiers.isEmpty ? '' : '${modifiers.join(' ')} ';
  final initializer = element.constantInitializer;
  final value = initializer == null ? '' : ' = ${initializer.toSource()}';
  buffer.writeln(
    '${indent}field $prefix${_type(element.type)} '
    '${element.displayName}$value',
  );
}

void _writeGetter(
  StringBuffer buffer,
  GetterElement element, {
  required String indent,
}) {
  final staticPrefix = element.isStatic ? 'static ' : '';
  buffer.writeln(
    '${indent}getter $staticPrefix${_type(element.returnType)} '
    '${element.displayName}',
  );
}

void _writeSetter(
  StringBuffer buffer,
  SetterElement element, {
  required String indent,
}) {
  final staticPrefix = element.isStatic ? 'static ' : '';
  buffer.writeln(
    '${indent}setter $staticPrefix${element.displayName}'
    '${_parameters(element.formalParameters)}',
  );
}

String _parameters(List<FormalParameterElement> parameters) {
  final requiredPositional = parameters
      .where((parameter) => parameter.isRequiredPositional)
      .map(_parameter)
      .toList();
  final optionalPositional = parameters
      .where((parameter) => parameter.isOptionalPositional)
      .map(_parameter)
      .toList();
  final named = parameters
      .where((parameter) => parameter.isNamed)
      .map(_parameter)
      .toList();

  final groups = <String>[
    ...requiredPositional,
    if (optionalPositional.isNotEmpty) '[${optionalPositional.join(', ')}]',
    if (named.isNotEmpty) '{${named.join(', ')}}',
  ];
  return '(${groups.join(', ')})';
}

String _parameter(FormalParameterElement parameter) {
  final requiredPrefix = parameter.isRequiredNamed ? 'required ' : '';
  final defaultValue = parameter.defaultValueCode;
  final defaultSuffix = defaultValue == null ? '' : ' = $defaultValue';
  return '$requiredPrefix${_type(parameter.type)} '
      '${parameter.displayName}$defaultSuffix';
}

String _typeParameters(TypeParameterizedElement element) {
  if (element.typeParameters.isEmpty) {
    return '';
  }
  final parameters = element.typeParameters.map((parameter) {
    final bound = parameter.bound;
    return bound == null
        ? parameter.displayName
        : '${parameter.displayName} extends ${_type(bound)}';
  });
  return '<${parameters.join(', ')}>';
}

String _type(DartType type) => type.getDisplayString();
